#! /bin/sh

# If refreshing bspwm, remove all previous rules to prevent doubling up.
bspc rule -r "*"

# default bspwm stuff
bspc config focus_follows_pointer true
pgrep -x sxhkd > /dev/null || sxhkd &
bspc monitor eDP-1 -d 1 2 3 4 5

bspc config border_width         2
bspc config window_gap          12
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

bspc config top_padding 22	# top_padding I set equal to polybar's height

# startup stuff
picom --shadow --round-borders 3 --corner-radius 3 --vsync &
redshift &
polybar --config=.config/polybar/config.ini example &
wal -R &
dunst &

# pywal support

# source the colors.
. "${HOME}/.cache/wal/colors.sh"

# Set the border colors.
bspc config normal_border_color "$color3"
bspc config active_border_color "$color3"
bspc config focused_border_color "$color3"
# Use the line below if you are on bspwm >= 0.9.4
bspc config presel_feedback_color "$color1"
# Use the line below if you are on bspwm < 0.9.4
#bspc config presel_border_color "$color1"

# scratchpad
#terminator -c scratchterm &
#bspc rule -a scratchterm sticky=on state=floating hidden=on

# cursor fix
xsetroot -cursor_name left_ptr &
reload_dunst.sh & 
feh --bg-fill /home/joel/media/images/wallpapers/grey-solid.png  

for monitor in $desktops; do
    [ "$IsInitialRun" = true ] && \
        bspc monitor "$monitor" -n $i -d $i/{00,01,10,11} || \
        bspc monitor "$monitor" -d $i/{00,01,10,11}
    let i++
done
